// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAir129A9lP7TiPPjuk_OAfI8Zqy92dl4g',
    appId: '1:938187528462:web:0a60fc97b70225af8a9f5f',
    messagingSenderId: '938187528462',
    projectId: 'swipe-fit',
    authDomain: 'swipe-fit.firebaseapp.com',
    storageBucket: 'swipe-fit.firebasestorage.app',
    measurementId: 'G-6M1N56YP8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdhsxCsL7eK1ZMYXbfFGpsuBd32uC34EU',
    appId: '1:938187528462:android:24d5c2fb8fe5d2ec8a9f5f',
    messagingSenderId: '938187528462',
    projectId: 'swipe-fit',
    storageBucket: 'swipe-fit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXW0mK3fcGRdLk6fN3edwCMle_xrMTaQg',
    appId: '1:938187528462:ios:56bfacf1155355558a9f5f',
    messagingSenderId: '938187528462',
    projectId: 'swipe-fit',
    storageBucket: 'swipe-fit.firebasestorage.app',
    iosBundleId: 'com.swipefit.swipefit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXW0mK3fcGRdLk6fN3edwCMle_xrMTaQg',
    appId: '1:938187528462:ios:56bfacf1155355558a9f5f',
    messagingSenderId: '938187528462',
    projectId: 'swipe-fit',
    storageBucket: 'swipe-fit.firebasestorage.app',
    iosBundleId: 'com.swipefit.swipefit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAir129A9lP7TiPPjuk_OAfI8Zqy92dl4g',
    appId: '1:938187528462:web:fa1e4425c5e98a918a9f5f',
    messagingSenderId: '938187528462',
    projectId: 'swipe-fit',
    authDomain: 'swipe-fit.firebaseapp.com',
    storageBucket: 'swipe-fit.firebasestorage.app',
    measurementId: 'G-3D891E9W6R',
  );
}
